# Generated by Django 4.2.20 on 2025-05-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
