# Generated by Django 4.2.20 on 2025-05-19 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0003_alter_provisionalresultrequest_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('form_4_certificate', 'Form 4 Certificate'), ('form_6_certificate', 'Form 6 Certificate'), ('diploma_certificate', 'Diploma Certificate'), ('voter_id', 'Voter ID'), ('nin_id', 'NIN ID')], max_length=50)),
                ('certificate_name', models.CharField(max_length=255)),
                ('certificate_file', models.FileField(upload_to='student_certificates/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
