# Generated by Django 4.2.20 on 2025-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_studentcertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='provisionalresultrequest',
            name='semester_range',
            field=models.CharField(choices=[('one', 'Semester I'), ('two', 'Semester II'), ('all', 'First Year to Second Year')], max_length=30),
        ),
    ]
