# Generated by Django 4.2.20 on 2025-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0004_remove_customuser_profile_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nida',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
