# Generated by Django 4.2.20 on 2025-06-14 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0005_customuser_phone_number_and_more'),
    ]

    operations = [
        # Use IF NOT EXISTS because 0008 (a parallel branch) may have already added these columns
        migrations.RunSQL(
            "ALTER TABLE users_api_profile ADD COLUMN IF NOT EXISTS webauthn_credential_id TEXT NULL",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "ALTER TABLE users_api_profile ADD COLUMN IF NOT EXISTS webauthn_public_key TEXT NULL",
            migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint_data', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
