# Generated by Django 4.2.20 on 2025-06-14 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0006_profile_webauthn_credential_id_and_more'),
        ('users_api', '0008_add_webauthn_fields_to_profile'),
    ]

    operations = [
    ]
