# Generated by Django 4.2.20 on 2025-06-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0011_alter_provisionalresultrequest_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='webauthn_credential_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='webauthn_public_key',
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='webauthn_credential_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='webauthn_public_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
