# Generated by Django 4.2.20 on 2025-06-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0012_remove_profile_webauthn_credential_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='webauthn_aaguid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='webauthn_attestation_format',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fingerprint',
            name='webauthn_sign_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
