# Generated by Django 4.2.20 on 2025-06-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0013_fingerprint_webauthn_aaguid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionalresultrequest',
            old_name='exam_officer_approved',
            new_name='exam_officer_verified',
        ),
        migrations.RenameField(
            model_name='transcriptcertificaterequest',
            old_name='exam_officer_approved',
            new_name='exam_officer_verified',
        ),
    ]
