# Generated by Django 4.2.20 on 2025-06-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0014_rename_exam_officer_approved_provisionalresultrequest_exam_officer_verified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provisionalresultrequest',
            old_name='exam_officer_verified',
            new_name='exam_officer_approved',
        ),
        migrations.RenameField(
            model_name='transcriptcertificaterequest',
            old_name='exam_officer_verified',
            new_name='exam_officer_approved',
        ),
    ]
