# Generated by Django 4.2.20 on 2025-06-16 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_api', '0015_rename_exam_officer_verified_provisionalresultrequest_exam_officer_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='A nickname to help the user identify this authenticator', max_length=250, null=True)),
                ('credential_id', models.BinaryField(max_length=256, unique=True)),
                ('public_key', models.BinaryField(max_length=512)),
                ('attestation_format', models.CharField(max_length=100)),
                ('aaguid', models.UUIDField(blank=True, null=True)),
                ('sign_count', models.PositiveIntegerField()),
                ('credential_type', models.CharField(default='public-key', max_length=50)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Device',
                'verbose_name_plural': 'WebAuthn Devices',
                'unique_together': {('user', 'credential_id')},
            },
        ),
        migrations.DeleteModel(
            name='Fingerprint',
        ),
    ]
